[[main]]
  name = "About"
  url = "#about"
  weight = 10
[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20
[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
